lyceum/about/urls.py
from django.urls import path
from django.views.generic import TemplateView


app_name = "about"

urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="about/about.html",
            extra_context={"title": "О проекте"},
        ),
        name="index-page",
    ),
]

lyceum/homepage/urls.py
from django.urls import path

import homepage.views

app_name = "homepage"

urlpatterns = [
    path(
        "",
        homepage.views.HomepageListView.as_view(),
        name="index-page",
    ),
    path(
        "coffee/",
        homepage.views.CoffeeListView.as_view(),
        name="coffee",
    ),
    path(
        "echo/",
        homepage.views.EchoView.as_view(),
        name="echo-page",
    ),
    path(
        "echo/submit/",
        homepage.views.EchoSubmitView.as_view(),
        name="echo-submit-page",
    ),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

app_name = "lyceum"

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("catalog/", include("catalog.urls")),
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("statistics/", include("stats.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        path(
            "__debug__/",
            include(debug_toolbar.urls),
        ),
    )

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

lyceum/stats/urls.py
from django.urls import path

import stats.views

app_name = "stats"

urlpatterns = [
    path(
        "users/<int:pk>/",
        stats.views.UserDetailView.as_view(),
        name="user-stats-detail",
    ),
    path("rated/", stats.views.RatedItemsView.as_view(), name="rated-items"),
    path(
        "items/<int:pk>/",
        stats.views.ItemDetailView.as_view(),
        name="item-stats-detail",
    ),
]

lyceum/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path


import users.views


app_name = "users"

urlpatterns = [
    path("user_list/", users.views.UserListView.as_view(), name="user-list"),
    path(
        "user_detail/<int:pk>/",
        users.views.UserDetailView.as_view(),
        name="user-detail",
    ),
    path("profile/", users.views.ProfileView.as_view(), name="user-profile"),
    path(
        "signup/",
        users.views.SignupView.as_view(),
        name="signup",
    ),
    path(
        "activate/<str:username>/",
        users.views.ActivateView.as_view(),
        name="activate",
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
]

urlpatterns_password_reset = [
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            success_url="done",
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change/done",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            success_url="done",
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += urlpatterns_password_reset

lyceum/users/models.py
from datetime import date

import django.conf
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(
        help_text="день рождения",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        help_text="аватарка",
        upload_to=f"{django.conf.settings.UPLOAD_TO_PATH}profile_images/",
        blank=True,
        null=True,
    )
    coffee_count = models.PositiveIntegerField(
        help_text="счетчик кофе",
        default=0,
    )

    class Meta:
        verbose_name = "профиль"
        verbose_name_plural = "профили"

    def __str__(self):
        return self.user.username

    def clean(self):
        if self.birthday > date.today():
            raise ValidationError("Выберите дату, которая не в будущем.")


__all__ = ()

lyceum/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

import users.models

User = get_user_model()


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text="Введите почту")

    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            User.username.field.name,
            User.email.field.name,
            "password1",
            "password2",
        )


class UserForm(UserChangeForm):
    password = None

    class Meta(UserChangeForm.Meta):
        model = User
        fields = (User.email.field.name, User.first_name.field.name)


class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["coffee_count"].widget.attrs["disabled"] = True
        self.fields["image"].required = False
        self.fields["coffee_count"].required = False

    class Meta:
        model = users.models.Profile
        fields = (
            users.models.Profile.birthday.field.name,
            users.models.Profile.image.field.name,
            users.models.Profile.coffee_count.field.name,
        )

        widgets = {
            "birthday": forms.DateInput(
                format="%Y-%m-%d",
                attrs={"type": "date"},
            ),
        }


__all__ = ()

lyceum/users/views.py
from datetime import timedelta

import django.conf
import django.contrib.auth.mixins
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import render
from django.utils import timezone

import users.forms
import users.models


class SignupView(django.views.generic.FormView):
    model = users.models.User
    form_class = users.forms.SignUpForm
    template_name = "users/signup.html"
    success_url = django.urls.reverse_lazy("homepage:index-page")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_active = django.conf.settings.DEFAULT_USER_IS_ACTIVE
        user.save()

        if not user.is_active:
            activation_link = (
                f"http://127.0.0.1:8000/auth/activate/{user.username}/"
            )

            send_mail(
                subject="Активация",
                message=activation_link,
                from_email=django.conf.settings.MAIL,
                recipient_list=[user.email],
                fail_silently=True,
            )

        return super().form_valid(form)


class ActivateView(django.views.generic.TemplateView):
    def get(self, request, username):
        user = User.objects.get(username=username)

        if user.date_joined + timedelta(hours=12) > timezone.now():
            user.is_active = True
            user.save()

            return render(
                request,
                "users/activation_success.html",
                {"title": "Успешная активация"},
            )

        return render(
            request,
            "users/activation_expired.html",
            {"title": "Ссылка просрочена"},
        )


class UserListView(django.views.generic.ListView):
    template_name = "users/user_list.html"
    context_object_name = "users"
    queryset = (
        User.objects.filter(is_active=True)
        .select_related("profile")
        .only(
            "username",
            "first_name",
            "last_name",
            "email",
            "profile__birthday",
            "profile__image",
            "profile__coffee_count",
        )
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Список пользователей"
        return context


class UserDetailView(django.views.generic.DetailView):
    template_name = "users/user_detail.html"
    context_object_name = "user"
    queryset = User.objects.only(
        "username",
        "first_name",
        "last_name",
        "email",
        "is_staff",
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Пользователь детально"
        return context


class ProfileView(
    django.contrib.auth.mixins.LoginRequiredMixin,
    django.views.generic.edit.ModelFormMixin,
    django.views.generic.DetailView,
):
    model = users.models.User
    template_name = "users/profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Профиль"
        return context

    def get(self, request):

        user_form = users.forms.UserForm(
            request.POST or None,
            instance=request.user,
        )
        profile_form = users.forms.ProfileForm(
            request.POST or None,
            request.FILES or None,
            instance=request.user.profile,
        )

        return render(
            request,
            self.template_name,
            {
                "user_form": user_form,
                "profile_form": profile_form,
            },
        )

    def post(self, request):
        user_form = users.forms.UserForm(
            request.POST or None,
            instance=request.user,
        )
        profile_form = users.forms.ProfileForm(
            request.POST or None,
            request.FILES or None,
            instance=request.user.profile,
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

        return render(
            request,
            self.template_name,
            {
                "user_form": user_form,
                "profile_form": profile_form,
            },
        )


__all__ = ()

lyceum/templates/users/activation_expired.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <h3>Ссылка активации просрочена!</h3>
    <p>Пожалуйста повторите регистрацию.</p>
</div>
{% endblock %}

lyceum/templates/users/activation_sent.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <h3>Ссылка активации отправлена, проверьте вашу почту.</h3>
    <a href="/">На главную</a>
</div>
{% endblock %}

lyceum/templates/users/activation_success.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <h1>Аккаунт активирован!</h1>
    <p>Вы успешно активировали свой аккаунт.</p>
</div>
{% endblock %}

lyceum/templates/users/login.html
{% extends "base.html" %}
{% block content %}
<div class="w-25 p-3 mx-auto">
    {% for message in messages %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Войти</button>
        <a href="{% url 'users:password_reset' %}">Забыли пароль?</a>
        <p>Нет аккаунта? <a href="{% url 'users:signup' %}">Зарегистрироваться</a></p>
    </form>
</div>
{% endblock %}

lyceum/templates/users/logout.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <h2>Вы вышли из системы</h2>
    <a class="btn btn-primary" href="{% url 'users:login' %}">Войти снова</a>
</div>
{% endblock %}

lyceum/templates/users/password_change.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сменить пароль</button>
    </form>
</div>
{% endblock %}

lyceum/templates/users/password_reset.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <h2>Сброс пароля</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Отправить ссылку для сброса пароля</button>
    </form>
</div>
{% endblock %}

lyceum/templates/users/password_reset_complete.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <h2>Ваш пароль успешно сброшен. Вы можете войти с новым паролем.</h2>
    <a href="{% url 'users:login' %}">Войти</a>
</div>
{% endblock %}

lyceum/templates/users/password_reset_confirm.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <h2>Введите новый пароль</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Сбросить пароль</button>
    </form>
</div>
{% endblock %}

lyceum/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <h2>Ссылка для сброса пароля была успешно отправлена на ваш email.</h2>
</div>
{% endblock %}

lyceum/templates/users/profile.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <h2>Мой профиль</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button class="btn btn-primary" type="submit">Сохранить изменения</button>
    </form>
    <br>
    <a class="btn btn-outline-secondary" href="{% url "homepage:coffee" %}" role="button">Выпить кофе</a>
    <a role="button" href="{% url "stats:rated-items" %}" class="btn btn-outline-secondary">Статистика</a>
    <br>
    <br>
    <br>
    <a role="button" href="{% url "users:logout" %}" class="btn btn-outline-danger">Выйти</a>
</div>
<script>
    const today = new Date().toISOString().split('T')[0];
    document.getElementById("id_birthday").setAttribute('max', today);
</script>
{% endblock %}

lyceum/templates/users/signup.html
{% extends "base.html" %}

{% block content %}
<div class="w-25 p-3 mx-auto">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">Зарегистрироваться</button>
    </form>
</div>
{% endblock %}

lyceum/templates/users/user_detail.html
{% extends "base.html" %}
{% load static%}


{% block content %}
<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
        <div class="col-10 col-sm-8 col-lg-6">
        <img
            {% if user.profile.image %}
            src="{{ user.profile.image.url }}"
            {% else %}
            src=""
            {% endif  %}
            class="d-block mx-lg-auto img-fluid rounded-circle border border-dark border-5"
            alt="Аватарка"
            width="250"
            height="250"
            loading="lazy"
        />
        </div>
        <div class="col-lg-6">
            <p class="display-6 lh-3 mb-3">Почта: {{ user.email }}</p>
            {% if user.first_name %}<p class="lead">Имя: {{ user.first_name|capfirst }}</p>{% else %}<p class="lead">Имя: <i>не указано</i></p>{% endif %}
            {% if user.last_name %}<p class="lead">Фамилия: {{ user.last_name|capfirst }}</p>{% else %}<p class="lead">Фамилия: <i>не указано</i></p>{% endif %}
            <p class="lead">День рождения: {{ user.profile.birthday|date:"d.m.Y" }}</p>
            <p class="lead">Сколько пытался выпить кофе: {{ user.profile.coffee_count }}</p>
        </div>
    </div>
</div>
{% endblock %}

lyceum/templates/users/user_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="w-50 p-3 mx-auto">
    <h2>Список активных пользователей</h2>
</div>
<div class="w-75 p-3 mx-auto">
<table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Имя</th>
        <th scope="col">День+Месяц даты рождения</th>
        <th scope="col">Изображение</th>
        <th scope="col">Статистика</th>
      </tr>
    </thead>
    <tbody>
        {% for user in users %}
            <tr>
                <th scope="row"><a href="{% url "users:user-detail" user.id %}">{{ user.id }}</a></th>
                <td>{{ user.username }}</td>
                <td>{{ user.profile.birthday|date:"d+m" }}</td>
                {% if user.profile.image %}
                    <td><img src="{{ user.profile.image.url }}"
                        class="rounded border"
                        alt="{{ user.profile.image.name }}"
                        width="60px"
                        height="60px" />
                    </td>
                {% else %}
                    <td></td>
                {% endif %}
                <td>
                  <a href={% url "stats:user-stats-detail" user.id %}>Посмотреть статистику</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
</div>
{% endblock content %}