lyceum/about/urls.py
from django.urls import path
from django.views.generic import TemplateView


app_name = "about"

urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="about/about.html",
            extra_context={"title": "О проекте"},
        ),
        name="index-page",
    ),
]

lyceum/catalog/urls.py
from django.urls import path

import catalog.converters
import catalog.views


app_name = "catalog"

urlpatterns = [
    path(
        "",
        catalog.views.ItemListView.as_view(),
        name="index-page",
    ),
    path(
        "<int:pk>/",
        catalog.views.ItemDetailView.as_view(),
        name="item-detail",
    ),
    path(
        "<int:pk>/delete_rating/",
        catalog.views.RatingDeleteView.as_view(),
        name="delete-rating",
    ),
    path(
        "new/",
        catalog.views.NewItemListView.as_view(),
        name="new-page",
    ),
    path(
        "friday/",
        catalog.views.FridayItemDetailView.as_view(),
        name="friday-page",
    ),
    path(
        "unverified/",
        catalog.views.UnverifiedItemListView.as_view(),
        name="unverified-page",
    ),
]

lyceum/homepage/urls.py
from django.urls import path

import homepage.views

app_name = "homepage"

urlpatterns = [
    path(
        "",
        homepage.views.HomepageListView.as_view(),
        name="index-page",
    ),
    path(
        "coffee/",
        homepage.views.CoffeeListView.as_view(),
        name="coffee",
    ),
    path(
        "echo/",
        homepage.views.EchoView.as_view(),
        name="echo-page",
    ),
    path(
        "echo/submit/",
        homepage.views.EchoSubmitView.as_view(),
        name="echo-submit-page",
    ),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

app_name = "lyceum"

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("catalog/", include("catalog.urls")),
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("statistics/", include("stats.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        path(
            "__debug__/",
            include(debug_toolbar.urls),
        ),
    )

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

lyceum/templates/includes/footer.html
{% load static %}
<div class="container">
  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3"></ul>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
       var currentYear = new Date().getFullYear();
       document.getElementById('currentYear').textContent = currentYear;
      });
    </script>
    <p class="text-center"> © <span class="text-center text-body-secondary" id="currentYear">{% now "Y" %}</span> Company, Inc</p>
  </footer>
</div>
<script>
  var timezoneOffset = new Date().getTimezoneOffset() / -60;
  document.cookie = "user_offset=" + timezoneOffset + "; path=/; max-age=" + (30 * 24 * 60 * 60);
</script>

lyceum/templates/includes/header.html
{% load static %}
{% load i18n %}
<div class="container">
<header
class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom"
>
    <a
    href="{% url 'homepage:index-page' %}"
    class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none"
    >
    <img
    class="bi me-2"
    width="40"
    height="32"
    role="img"
    alt="Icon"
    src="{% static 'img/favicon.svg' %}"
    />
    </a>
  {% with request.resolver_match.view_name as view_name %}
  <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
    <li>
      <a {% if view_name != "homepage:index-page" %} href="{% url 'homepage:index-page' %}"{% endif %} class="nav-link px-2 link{% if view_name == 'homepage:index-page' %}-secondary active{% endif %}">Главная</a>
    </li>
    <li>
      <a {% if view_name != "catalog:index-page" %} href="{% url 'catalog:index-page' %}"{% endif %} class="nav-link px-2 link{% if view_name == 'catalog:index-page' %}-secondary active{% endif %}">Каталог</a
      >
    </li>
    <li>
      <a {% if view_name != "about:index-page" %} href="{% url 'about:index-page' %}"{% endif %} class="nav-link px-2 link{% if view_name == 'about:index-page' %}-secondary active{% endif %}">О проекте</a>
    </li>
    <li>
      <a {% if view_name != "feedback:feedback" %} href="{% url 'feedback:feedback' %}"{% endif %} class="nav-link px-2 link{% if view_name == 'feedback:feedback' %}-secondary active{% endif %}">Обратная связь</a>
    </li>
    <li>
      <a {% if view_name != "catalog:friday-page" %} href="{% url 'catalog:friday-page' %}"{% endif %} class="nav-link px-2 link{% if view_name == 'catalog:friday-page' %}-secondary active{% endif %}">Пятница</a>
    </li>
    <li>
      <a {% if view_name != "users:user-list" %} href="{% url 'users:user-list' %}"{% endif %} class="nav-link px-2 link{% if view_name == 'users:user-list' %}-secondary active{% endif %}">Список пользователей</a>
    </li>
    {% if request.user.is_authenticated %}
    <li>
      <a {% if view_name != "users:user-profile" %} href="{% url 'users:user-profile' %}"{% endif %} class="nav-link px-2 link{% if view_name == 'users:user-profile' %}-secondary active{% endif %}">Профиль</a>
    </li>
    {% else %}
    <li>
      <a {% if view_name != "users:login" %} href="{% url 'users:login' %}"{% endif %} class="nav-link px-2 link{% if view_name == 'users:login' %}-secondary active{% endif %}">Вход</a>
    </li>
    {% endif %}
    {% if request.user.is_superuser %}
    <li>
      <a href="{% url 'admin:index' %}" class="btn btn-outline-primary"> Админка</a>
    </li>
    {% endif %}
  </ul>
  {% endwith %}
</header>
{% if birthday_people %}
  <div class="alert alert-dark" role="alert">
    Сегодня день рождения у:
    {% for man in birthday_people %}
    <span
    class="border border-dark rounded-1 text-dark"
    >{% if man.first_name %}{{ man.first_name }}{% endif %} {% if man.email %}{{ man.email }}{% endif %}</span>{% if not forloop.last %}, {% endif %}
    {% endfor %}
  </div>
{% endif %}
</div>

lyceum/templates/includes/item_card.html
{% load static %}
{% load i18n %}

<div class="col">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ item.name|capfirst }}</h5>
        <p class="card-text">{{ item.text|safe|truncatewords_html:10 }}</p>
      </div>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Категория:
          <span class="border border-3 border-info bg-info rounded-2 text-white"
            >{{ item.category.name }}</span
          >
        </li>
        <li class="list-group-item">
          Тег: {% for tag in item.tags.all %}<span
            class="border border-3 border-primary bg-primary rounded-2 text-white"
            >{{ tag }}</span
          >{% endfor %}
        </li>
      </ul>
      <div class="card-body">
        <a href="{% url 'catalog:item-detail' item.id %}" class="card-link"
          >Подробнее</a
        >
      </div>
    </div>
  </div>