lyceum/about/urls.py
from django.urls import path
from django.views.generic import TemplateView


app_name = "about"

urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="about/about.html",
            extra_context={"title": "О проекте"},
        ),
        name="index-page",
    ),
]

lyceum/catalog/urls.py
from django.urls import path

import catalog.converters
import catalog.views


app_name = "catalog"

urlpatterns = [
    path(
        "",
        catalog.views.ItemListView.as_view(),
        name="index-page",
    ),
    path(
        "<int:pk>/",
        catalog.views.ItemDetailView.as_view(),
        name="item-detail",
    ),
    path(
        "<int:pk>/delete_rating/",
        catalog.views.RatingDeleteView.as_view(),
        name="delete-rating",
    ),
    path(
        "new/",
        catalog.views.NewItemListView.as_view(),
        name="new-page",
    ),
    path(
        "friday/",
        catalog.views.FridayItemDetailView.as_view(),
        name="friday-page",
    ),
    path(
        "unverified/",
        catalog.views.UnverifiedItemListView.as_view(),
        name="unverified-page",
    ),
]

lyceum/download/urls.py
from django.urls import path

import download.views


app_name = "download"

urlpatterns = [
    path(
        "<path:path_to_file>/",
        download.views.DownloadDetailView.as_view(),
        name="download-page",
    ),
]

lyceum/lyceum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

app_name = "lyceum"

urlpatterns = [
    path("", include("homepage.urls")),
    path("about/", include("about.urls")),
    path("catalog/", include("catalog.urls")),
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("download/", include("download.urls")),
    path("feedback/", include("feedback.urls")),
    path("statistics/", include("stats.urls")),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        path(
            "__debug__/",
            include(debug_toolbar.urls),
        ),
    )

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

lyceum/stats/urls.py
from django.urls import path

import stats.views

app_name = "stats"

urlpatterns = [
    path(
        "users/<int:pk>/",
        stats.views.UserDetailView.as_view(),
        name="user-stats-detail",
    ),
    path("rated/", stats.views.RatedItemsView.as_view(), name="rated-items"),
    path(
        "items/<int:pk>/",
        stats.views.ItemDetailView.as_view(),
        name="item-stats-detail",
    ),
]

lyceum/users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path


import users.views


app_name = "users"

urlpatterns = [
    path("user_list/", users.views.UserListView.as_view(), name="user-list"),
    path(
        "user_detail/<int:pk>/",
        users.views.UserDetailView.as_view(),
        name="user-detail",
    ),
    path("profile/", users.views.ProfileView.as_view(), name="user-profile"),
    path(
        "signup/",
        users.views.SignupView.as_view(),
        name="signup",
    ),
    path(
        "activate/<str:username>/",
        users.views.ActivateView.as_view(),
        name="activate",
    ),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="users/login.html",
        ),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(
            template_name="users/logout.html",
        ),
        name="logout",
    ),
]

urlpatterns_password_reset = [
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            success_url="done",
            template_name="users/password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change/done",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html",
        ),
        name="password_change",
    ),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            success_url="done",
            template_name="users/password_reset.html",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += urlpatterns_password_reset

lyceum/catalog/models.py
import re

import django.conf
import django.core.exceptions
import django.core.validators
import django.db.models
import django.utils.safestring
import sorl.thumbnail
import tinymce
import tinymce.models
import transliterate
import transliterate.exceptions


import catalog.managers
import catalog.models
import catalog.validators
import core.models


ONLY_LETTERS_REGEX = re.compile(r"[^\w]")


def normalize(text):
    try:
        transliterated = transliterate.translit(
            text.lower(),
            reversed=True,
            language_code="ru",
        )
    except transliterate.exceptions.LanguageDetectionError:
        transliterated = text.lower()

    return ONLY_LETTERS_REGEX.sub(
        "",
        transliterated,
    )


class Tag(core.models.AbstractModel):
    slug = django.db.models.SlugField(
        "слаг",
        max_length=200,
        unique=True,
        help_text="введите слаг",
    )

    normalized_name = django.db.models.CharField(
        "нормализированное имя",
        max_length=150,
        unique=False,
        blank=True,
        default=None,
        null=True,
    )

    class Meta:
        verbose_name = "тег"
        verbose_name_plural = "теги"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.normalized_name = normalize(self.name)
        super().save(**kwargs)

    def clean(self):
        if Tag.objects.filter(normalized_name=normalize(self.name)):
            raise django.core.exceptions.ValidationError(
                "Тег с похожим названием уже существует",
            )


class Category(core.models.AbstractModel):
    slug = django.db.models.SlugField(
        "слаг",
        max_length=200,
        unique=True,
        help_text="введите слаг",
    )
    weight = django.db.models.PositiveSmallIntegerField(
        "вес",
        default=100,
        validators=[catalog.validators.validate_int_from_1_to_32767],
        help_text="введите вес",
    )

    normalized_name = django.db.models.CharField(
        "нормализированное имя",
        max_length=150,
        unique=False,
        blank=True,
        default=None,
        null=True,
    )

    class Meta:
        verbose_name = "категория"
        verbose_name_plural = "категории"

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.normalized_name = normalize(self.name)
        super().save(**kwargs)

    def clean(self):
        if Category.objects.filter(normalized_name=normalize(self.name)):
            raise django.core.exceptions.ValidationError(
                "Категория с похожим названием уже существует",
            )


class Item(core.models.AbstractModel):
    text = tinymce.models.HTMLField(
        "текст",
        validators=[
            catalog.validators.ValidateMustContain("роскошно", "превосходно"),
        ],
        help_text="введите текст",
    )
    category = django.db.models.ForeignKey(
        Category,
        on_delete=django.db.models.CASCADE,
        default=None,
        related_name="items",
        related_query_name="item",
    )
    tags = django.db.models.ManyToManyField(
        Tag,
        related_name="items",
        related_query_name="item",
    )

    is_on_main = django.db.models.BooleanField(
        "принадлежит к главной странице",
        default=False,
        help_text="введите принадлежит ли к главной странице товар",
    )
    created_at = django.db.models.DateTimeField(
        "дата создания",
        auto_now_add=True,
        null=True,
    )
    updated_at = django.db.models.DateTimeField(
        "обновлено",
        auto_now=True,
        null=True,
    )

    objects = catalog.managers.ItemManager()

    def image_tmb(self):
        if self.main_image:
            return django.utils.safestring.mark_safe(
                f"<img src='{self.main_image.image.url}' width='50'>",
            )

        return "Нет изображения"

    image_tmb.short_description = "превью"
    image_tmb.allow_tags = True

    class Meta:
        verbose_name = "товар"
        verbose_name_plural = "товары"

    def __str__(self):
        return self.name


class MainImage(django.db.models.Model):
    image = django.db.models.ImageField(
        "изображение",
        upload_to=django.conf.settings.UPLOAD_TO_PATH,
    )

    item = django.db.models.OneToOneField(
        "Item",
        on_delete=django.db.models.CASCADE,
        null=True,
        blank=True,
        verbose_name="id айтема",
        to_field="id",
        related_name="main_image",
    )

    def get_image_300x300(self):
        return sorl.thumbnail.get_thumbnail(self.image, "300", quality=51)

    class Meta:
        verbose_name = "изображение"
        verbose_name_plural = "изображения"

    def __str__(self):
        return self.image.name[:20]


class GalleryImage(django.db.models.Model):
    image = django.db.models.ImageField(
        "изображение",
        upload_to=django.conf.settings.UPLOAD_TO_PATH,
        default=None,
    )

    item = django.db.models.ForeignKey(
        "Item",
        on_delete=django.db.models.CASCADE,
        null=True,
        blank=True,
        verbose_name="id айтема",
        to_field="id",
        related_name="images",
    )

    class Meta:
        verbose_name = "изображения"
        verbose_name_plural = "изображения"

    def __str__(self):
        return self.image.name[:20]


__all__ = ()

lyceum/catalog/views.py
import datetime

from django.db.models import (
    Avg,
    Count,
    DurationField,
    ExpressionWrapper,
    F,
)
import django.http
import django.shortcuts
import django.urls
import django.utils
import django.views.generic
import django.views.generic.edit


import catalog.managers
import catalog.models
import rating.forms
import rating.models


class ItemListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    queryset = catalog.models.Item.objects.published().only(
        catalog.models.Item.name.field.name,
        catalog.models.Item.text.field.name,
        catalog.models.Item.category.field.name,
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Список товаров"
        return context


class ItemDetailView(
    django.views.generic.edit.FormMixin,
    django.views.generic.DetailView,
):
    form_class = rating.forms.RatingForm
    template_name = "catalog/item.html"
    context_object_name = "item"
    queryset = catalog.models.Item.objects.item_detail_published()

    def get_object(self, queryset=None):
        self.item = super().get_object(queryset)
        self.ratings = rating.models.Rating.objects.filter(item=self.item)
        if self.request.user.is_authenticated:
            self.user_rating = self.ratings.filter(
                user=self.request.user,
            ).first()
        else:
            self.user_rating = None

        return self.item

    def dispatch(self, request, *args, **kwargs):
        if request.method == "POST":
            self.ratings = rating.models.Rating.objects.filter(
                item=self.get_object(self.queryset),
            )
            self.user_rating = self.ratings.filter(
                user=self.request.user,
            ).first()

        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        rating_stats = self.ratings.aggregate(
            Avg(rating.models.Rating.score.field.name),
            Count(rating.models.Rating.score.field.name),
        )
        user_rating = self.user_rating

        context["average_rating"] = rating_stats["score__avg"]
        context["rating_count"] = rating_stats["score__count"]
        context["user_rating"] = user_rating
        context["title"] = self.item
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        user_rating = self.user_rating
        if user_rating:
            kwargs["initial"]["score"] = user_rating.score
        else:
            kwargs["initial"]["score"] = 0

        return kwargs

    def form_valid(self, form):
        score = form.cleaned_data["score"]
        rating.models.Rating.objects.update_or_create(
            user=self.request.user,
            item=self.item,
            defaults={"score": score},
        )
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            return self.form_valid(form)

        return self.form_invalid(form)

    def get_success_url(self):

        return django.shortcuts.reverse(
            "catalog:item-detail",
            kwargs={"pk": self.item.id},
        )


class RatingDeleteView(django.views.generic.DeleteView):
    def post(self, request, pk):

        item = django.shortcuts.get_object_or_404(catalog.models.Item, id=pk)

        if request.user.is_authenticated and request.method == "POST":
            rating.models.Rating.objects.filter(
                item=item,
                user=request.user,
            ).delete()

        return django.shortcuts.redirect(
            "catalog:item-detail",
            pk=pk,
        )


class FridayItemDetailView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    item_published = catalog.models.Item.objects.published()
    queryset = item_published.filter(updated_at__week_day=6).order_by(
        "-updated_at",
    )[:5]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Пятница"
        return context


class NewItemListView(django.views.generic.ListView):
    template_name = "homepage/main.html"
    context_object_name = "items"
    week_ago = django.utils.timezone.now() - datetime.timedelta(weeks=1)
    item_published = catalog.models.Item.objects.published()
    queryset = item_published.filter(created_at__gte=week_ago).order_by("?")[
        :5
    ]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Новинки"
        return context


class UnverifiedItemListView(django.views.generic.ListView):
    template_name = "catalog/item_list.html"
    context_object_name = "items"
    item_published = catalog.models.Item.objects.published()
    queryset = item_published.annotate(
        time_difference=ExpressionWrapper(
            F(catalog.models.Item.updated_at.field.name)
            - F(catalog.models.Item.created_at.field.name),
            output_field=DurationField(),
        ),
    ).filter(time_difference__lte=datetime.timedelta(seconds=1))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Непроверенное"
        return context


__all__ = ()

lyceum/templates/catalog/item.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container col-xxl-8 px-4 py-5">
  <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
    <div class="col-10 col-sm-8 col-lg-6">
      <img
        src="{{ item.main_image.image.url }}"
        class="d-block mx-lg-auto img-fluid"
        alt="{{item.name}}"
        width="700"
        height="500"
        loading="lazy"
      />
    </div>
    <div class="col-lg-6">
      <h1 class="display-5 fw-bold lh-1 mb-3">{{item.name|capfirst}}</h1>
      <p class="lead">{{item.text|safe|capfirst}}</p>
      <p class="lead fw-bolder">Категория: {{item.category.name|capfirst}}</p>
      <p class="lead fw-bolder">
        Тег: {% for tag in item.tags.all %} {{tag.name|capfirst}}{% if not forloop.last %},{% endif %} {% empty %} Список тегов пуст! {% endfor %}
      </p>

      {% if user.is_authenticated %}
        <p class="lead fw-bolder">
          Средняя оценка: {{ average_rating|floatformat:1 }} ({{ rating_count }} оценок)
        </p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-primary" type="submit">Поставить оценку</button>
        </form>
      {% else %}
        <p>Для того чтобы оставить оценку, пожалуйста, <a href="{% url 'users:login' %}">войдите</a>.</p>
      {% endif %}
      <br>
      {% if user_rating %}
       <form method="post" action="{% url 'catalog:delete-rating' pk=item.id %}">
           {% csrf_token %}
           <button class="btn btn-outline-danger" type="submit">Удалить оценку</button>
       </form>
       {% endif %}
       <button class="btn btn-outline-secondary">
          <a href={% url 'stats:item-stats-detail' pk=item.id %}>Статистика</a>
       </button>
      <br>
      {% if item.main_image %}
        <a href="{% url 'download:download-page' item.main_image.image %}" class="btn btn-primary">Скачать основную картинку</a>
      {% endif %}
    </div>
  </div>
  {% if item.images.all %}
  <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
    <p class="fs-2">Дополнительные изображения</p>
    <div class="text-left">
      {% for img in item.images.all %}
        <a href="{% url 'download:download-page' img.image %}">
          <img
            src="{{ img.image.url }}"
            class="rounded border"
            alt="test_preview.png"
            width="200x"
            height="200px"
          />
        </a>
      {% endfor %}
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

lyceum/templates/catalog/item_list.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block content %}
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Каталог категорий</h1>
      <p class="lead text-muted">Это каталог категоий товаров</p>
    </div>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for item_category in items %}
      {% ifchanged item_category.category.name %}
      <div class="col">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ item_category.category.name|capfirst }}</h5>
          </div>
          <ul class="list-group list-group-flush">
            {% for item in items %}
            
            {% if item.category.name == item_category.category.name %}
            <li class="list-group-item">
              <b>Товар:</b>
              <span class="border border-3 border-info bg-info rounded-2 text-white"
                >{{ item.name }}</span
              >
              <p class="card-text"><b>Описание:</b> {{ item.text|safe|truncatewords_html:10 }}</p>
              <p>
              Тег: {% for i in item.tags.all %}<span
                class="border border-3 border-primary bg-primary rounded-2 text-white"
                >{{ i }}</span
              >{% endfor %}
              </p>
              <p><a href="{% url 'catalog:item-detail' item.id %}" class="card-link"
                >Подробнее</a
              ></p>
            </li>
            {% endif %}
            {% endfor %}
          </ul>
        </div>
      </div>
      {% endifchanged %}
      {% empty %} Пустой список, ошибка!!! {% endfor %}
    </div>    
  </div>
</div>
{% endblock content %}